export const GET_PAGES = "GET_PAGES";
export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_INCOMING = "GET_MOVIE_INCOMING";
export const GET_MOVIE_DASHBOARD = "GET_MOVIE_DASHBOARD";
export const GET_MOVIE_SEARCH_DASHBOARD = "GET_MOVIE_SEARCH_DASHBOARD";
export const GET_INFORMATION_CINEMA = "GET_INFORMATION_CINEMA";
export const GET_SCHEDULES_CINEMA = "GET_SCHEDULES_CINEMA";
export const GET_MOVIE_BOXBOOKING = "GET_MOVIE_BOXBOOKING";
export const GET_CINEMA_BOXBOOKING = "GET_CINEMA_BOXBOOKING";
export const GET_CINEMA_CHECKOUT = "GET_CINEMA_CHECKOUT";
export const GET_USER_LIST_DASHBOARD = "GET_USER_LIST_DASHBOARD";
export const GET_USER_SEARCH_DASHBOARD = "GET_USER_SEARCH_DASHBOARD";
export const GET_USER_DETAIL = "GET_USER_DETAIL";

export const SET_TRAILER = "SET_TRAILER";
export const SET_MODAL_TRAILER = "SET_MODAL_TRAILER";
export const SET_MODAL_COMMENTS = "SET_MODAL_COMMENTS";
export const SET_MODAL_COMBO = "SET_MODAL_COMBO";
export const SET_MOVIE_SEARCH = "SET_MOVIE_SEARCH";
export const SET_TITLE_DASHBOARD = "SET_TITLE_DASHBOARD";
export const SET_TOKEN = "SET_TOKEN";
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_TICKET_BOOKING = "SET_TICKET_BOOKING";

export const REMOVE_TOKEN = "REMOVE_TOKEN";
export const CLEAR_MOVIE_LIST = "CLEAR_MOVIE_LIST";
export const DELETE_CINEMA_DATA = "DELETE_CINEMA_DATA";
export const CHANGE_USER_INFORMATION = "CHANGE_USER_INFORMATION";
